name: Docker Image CI

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "DATETIME=$(date --utc --rfc-3339=seconds | cut -c 1-19 | sed 's/[ :]/-/g')" >> $GITHUB_ENV
    - name: Test
      run: echo $DATETIME
